version: '3.8'

services:

  web:
    build: caseclub_back
    command: uvicorn caseclub_back.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./caseclub_back:/usr/src/caseclub_back
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/caseclub
    depends_on:
      - db

  db:
    image: postgres:13.4
    ports:
      - 5433:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=caseclub