version: '3.8'

services:

  # web:
  #   build: caseclub_back
  #   command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
  #   volumes:
  #     - ./project:/usr/src/app
  #   ports:
  #     - 8080:8000
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/caseclub
  #   depends_on:
  #     - db

  db:
    image: postgres:13.4
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=caseclub